/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BirthChartRouteImport } from './routes/birth-chart'
import { Route as HoroscopeRouteImport } from './routes/horoscope'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthChartRoute = BirthChartRouteImport.update({
  id: '/birth-chart',
  path: '/birth-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeRoute = HoroscopeRouteImport.update({
  id: '/horoscope',
  path: '/horoscope',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birth-chart': typeof BirthChartRoute
  '/horoscope': typeof HoroscopeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/birth-chart': typeof BirthChartRoute
  '/horoscope': typeof HoroscopeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/birth-chart': typeof BirthChartRoute
  '/horoscope': typeof HoroscopeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/birth-chart' | '/horoscope'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/birth-chart' | '/horoscope'
  id: '__root__' | '/' | '/birth-chart' | '/horoscope'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BirthChartRoute: typeof BirthChartRoute
  HoroscopeRoute: typeof HoroscopeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birth-chart': {
      id: '/birth-chart'
      path: '/birth-chart'
      fullPath: '/birth-chart'
      preLoaderRoute: typeof BirthChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope': {
      id: '/horoscope'
      path: '/horoscope'
      fullPath: '/horoscope'
      preLoaderRoute: typeof HoroscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BirthChartRoute: BirthChartRoute,
  HoroscopeRoute: HoroscopeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
